import { buildDataset } from './lib/heuristics'
import type { NormalizedEvent, ParsedDataset } from './types'

const sampleEvents: NormalizedEvent[] = [
  {
    id: 'event-1',
    category: 'chat',
    sourceFile: 'sample/chats.json',
    timestamp: '2026-02-08T00:41:00.000Z',
    contact: 'Jordan K',
    text: 'Miss you already. Delete this after you read it.',
    detail: null,
    locationName: null,
    latitude: null,
    longitude: null,
    device: null,
    region: null,
  },
  {
    id: 'event-2',
    category: 'chat',
    sourceFile: 'sample/chats.json',
    timestamp: '2026-02-09T01:14:00.000Z',
    contact: 'Jordan K',
    text: 'When can I see you again?',
    detail: null,
    locationName: null,
    latitude: null,
    longitude: null,
    device: null,
    region: null,
  },
  {
    id: 'event-3',
    category: 'search',
    sourceFile: 'sample/search.json',
    timestamp: '2026-02-09T01:10:00.000Z',
    contact: 'Jordan K',
    text: null,
    detail: 'JordanK87',
    locationName: null,
    latitude: null,
    longitude: null,
    device: null,
    region: null,
  },
  {
    id: 'event-4',
    category: 'location',
    sourceFile: 'sample/location.json',
    timestamp: '2026-02-09T01:30:00.000Z',
    contact: null,
    text: null,
    detail: null,
    locationName: 'Downtown hotel district',
    latitude: 40.7127,
    longitude: -74.0059,
    device: null,
    region: 'New York',
  },
  {
    id: 'event-5',
    category: 'login',
    sourceFile: 'sample/login.json',
    timestamp: '2026-02-09T01:03:00.000Z',
    contact: null,
    text: null,
    detail: 'Successful login',
    locationName: null,
    latitude: null,
    longitude: null,
    device: 'iPhone 15 Pro',
    region: 'New York',
  },
  {
    id: 'event-6',
    category: 'chat',
    sourceFile: 'sample/chats.json',
    timestamp: '2026-02-10T00:18:00.000Z',
    contact: 'Jordan K',
    text: 'Thinking about you.',
    detail: null,
    locationName: null,
    latitude: null,
    longitude: null,
    device: null,
    region: null,
  },
  {
    id: 'event-7',
    category: 'memory',
    sourceFile: 'sample/memories.json',
    timestamp: '2026-02-10T00:22:00.000Z',
    contact: null,
    text: null,
    detail: 'IMG_2003.MP4',
    locationName: 'Downtown hotel district',
    latitude: null,
    longitude: null,
    device: null,
    region: null,
  },
]

export const sampleDataset: ParsedDataset = buildDataset(sampleEvents)
