import type { ParsedUpload } from './types'

const chatEvents = [
  ['2026-02-08T00:41:00.000Z', 'Jordan K', 'Miss you already. Delete this after you read it.'],
  ['2026-02-08T18:13:00.000Z', 'Mia S', 'Can you send me the address later?'],
  ['2026-02-08T22:04:00.000Z', 'Chris P', 'You still up tonight?'],
  ['2026-02-09T01:14:00.000Z', 'Jordan K', 'When can I see you again?'],
  ['2026-02-09T09:22:00.000Z', 'Mia S', 'Here is the link https://example.com/venue'],
  ['2026-02-09T21:55:00.000Z', 'Chris P', 'Thinking about you.'],
  ['2026-02-10T00:18:00.000Z', 'Jordan K', 'Thinking about you.'],
  ['2026-02-10T00:26:00.000Z', 'Jordan K', 'Keep this between us for now.'],
  ['2026-02-10T13:02:00.000Z', 'Mia S', 'Email me at mia.s@example.com when you can.'],
  ['2026-02-11T23:16:00.000Z', 'Chris P', 'Come over when you are done.'],
  ['2026-02-12T00:10:00.000Z', 'Jordan K', 'Wish you were here.'],
  ['2026-02-12T17:44:00.000Z', 'Mia S', 'Lunch tomorrow?'],
  ['2026-02-13T00:21:00.000Z', 'Jordan K', 'Do not tell anyone I messaged you.'],
  ['2026-02-13T20:03:00.000Z', 'Chris P', 'Meet me by the hotel lobby.'],
  ['2026-02-14T00:44:00.000Z', 'Jordan K', 'I miss you.'],
] as const

export const sampleUpload: ParsedUpload = {
  upload: {
    id: 'sample-upload',
    fileName: 'sample-export.zip',
    sizeBytes: 24892,
    uploadedAt: '2026-02-14T00:00:00.000Z',
    processedAt: '2026-02-14T00:00:00.000Z',
    totalFiles: 8,
    supportedFiles: 8,
    unsupportedFiles: 0,
    categoryCounts: {
      account: 2,
      chat: 15,
      search: 3,
      location: 3,
      login: 2,
      memory: 2,
      friend: 2,
    },
    account: {
      username: 'alex.viewer',
      displayName: 'Alex Viewer',
      email: 'alex.viewer@example.com',
      phone: '+1 555 555 0199',
      region: 'New York',
      aliases: ['alex.viewer', 'Alex Viewer', 'alex.viewer@example.com'],
    },
    warnings: ['Sample workspace loaded for demonstration.'],
  },
  fileSummaries: [
    { uploadId: 'sample-upload', path: 'account/profile.json', extension: '.json', category: 'account', rows: 2, supported: true },
    { uploadId: 'sample-upload', path: 'chat/saved_chat_history.json', extension: '.json', category: 'chat', rows: 15, supported: true },
    { uploadId: 'sample-upload', path: 'search/search_history.json', extension: '.json', category: 'search', rows: 3, supported: true },
    { uploadId: 'sample-upload', path: 'location/location_history.json', extension: '.json', category: 'location', rows: 3, supported: true },
    { uploadId: 'sample-upload', path: 'login/login_history.json', extension: '.json', category: 'login', rows: 2, supported: true },
    { uploadId: 'sample-upload', path: 'friends/friends.json', extension: '.json', category: 'friend', rows: 2, supported: true },
    { uploadId: 'sample-upload', path: 'memories/memories_history.json', extension: '.json', category: 'memory', rows: 2, supported: true },
  ],
  events: [
    {
      id: 'sample-upload:account:1',
      uploadId: 'sample-upload',
      category: 'account',
      subtype: 'profile',
      sourceFile: 'account/profile.json',
      timestamp: '2026-02-08T00:00:00.000Z',
      contact: 'Alex Viewer',
      text: null,
      detail: 'alex.viewer@example.com',
      locationName: 'New York',
      latitude: null,
      longitude: null,
      device: 'iPhone 15 Pro',
      region: 'New York',
      evidenceText: 'Alex Viewer alex.viewer@example.com New York',
      attributes: { username: 'alex.viewer', email: 'alex.viewer@example.com' },
    },
    ...chatEvents.map(([timestamp, contact, text], index) => ({
      id: `sample-upload:chat:${index + 1}`,
      uploadId: 'sample-upload',
      category: 'chat' as const,
      subtype: 'saved message',
      sourceFile: 'chat/saved_chat_history.json',
      timestamp,
      contact,
      text,
      detail: null,
      locationName: null,
      latitude: null,
      longitude: null,
      device: null,
      region: null,
      evidenceText: text,
      attributes: { message: text },
    })),
    {
      id: 'sample-upload:search:1',
      uploadId: 'sample-upload',
      category: 'search',
      subtype: 'query',
      sourceFile: 'search/search_history.json',
      timestamp: '2026-02-09T01:10:00.000Z',
      contact: 'Jordan K',
      text: null,
      detail: '@JordanK87',
      locationName: null,
      latitude: null,
      longitude: null,
      device: null,
      region: null,
      evidenceText: '@JordanK87',
      attributes: { query: '@JordanK87' },
    },
    {
      id: 'sample-upload:search:2',
      uploadId: 'sample-upload',
      category: 'search',
      subtype: 'query',
      sourceFile: 'search/search_history.json',
      timestamp: '2026-02-10T20:15:00.000Z',
      contact: 'Chris P',
      text: null,
      detail: '@ChrisPlays',
      locationName: null,
      latitude: null,
      longitude: null,
      device: null,
      region: null,
      evidenceText: '@ChrisPlays',
      attributes: { query: '@ChrisPlays' },
    },
    {
      id: 'sample-upload:search:3',
      uploadId: 'sample-upload',
      category: 'search',
      subtype: 'query',
      sourceFile: 'search/search_history.json',
      timestamp: '2026-02-12T12:25:00.000Z',
      contact: 'Mia S',
      text: null,
      detail: '@mia.s',
      locationName: null,
      latitude: null,
      longitude: null,
      device: null,
      region: null,
      evidenceText: '@mia.s',
      attributes: { query: '@mia.s' },
    },
    {
      id: 'sample-upload:location:1',
      uploadId: 'sample-upload',
      category: 'location',
      subtype: 'snap map',
      sourceFile: 'location/location_history.json',
      timestamp: '2026-02-09T01:30:00.000Z',
      contact: null,
      text: null,
      detail: null,
      locationName: 'Downtown hotel district',
      latitude: 40.7127,
      longitude: -74.0059,
      device: null,
      region: 'New York',
      evidenceText: 'Downtown hotel district New York',
      attributes: { location: 'Downtown hotel district' },
    },
    {
      id: 'sample-upload:location:2',
      uploadId: 'sample-upload',
      category: 'location',
      subtype: 'snap map',
      sourceFile: 'location/location_history.json',
      timestamp: '2026-02-12T00:31:00.000Z',
      contact: null,
      text: null,
      detail: null,
      locationName: 'Riverfront apartments',
      latitude: 40.718,
      longitude: -74.001,
      device: null,
      region: 'New York',
      evidenceText: 'Riverfront apartments New York',
      attributes: { location: 'Riverfront apartments' },
    },
    {
      id: 'sample-upload:location:3',
      uploadId: 'sample-upload',
      category: 'location',
      subtype: 'snap map',
      sourceFile: 'location/location_history.json',
      timestamp: '2026-02-13T20:22:00.000Z',
      contact: null,
      text: null,
      detail: null,
      locationName: 'Hotel lobby',
      latitude: 40.717,
      longitude: -74.003,
      device: null,
      region: 'New York',
      evidenceText: 'Hotel lobby New York',
      attributes: { location: 'Hotel lobby' },
    },
    {
      id: 'sample-upload:login:1',
      uploadId: 'sample-upload',
      category: 'login',
      subtype: 'successful login',
      sourceFile: 'login/login_history.json',
      timestamp: '2026-02-09T01:03:00.000Z',
      contact: null,
      text: null,
      detail: 'Successful login',
      locationName: null,
      latitude: null,
      longitude: null,
      device: 'iPhone 15 Pro',
      region: 'New York',
      evidenceText: 'Successful login iPhone 15 Pro',
      attributes: { status: 'Successful login' },
    },
    {
      id: 'sample-upload:login:2',
      uploadId: 'sample-upload',
      category: 'login',
      subtype: 'successful login',
      sourceFile: 'login/login_history.json',
      timestamp: '2026-02-13T19:57:00.000Z',
      contact: null,
      text: null,
      detail: 'Successful login',
      locationName: null,
      latitude: null,
      longitude: null,
      device: 'iPad Pro',
      region: 'New York',
      evidenceText: 'Successful login iPad Pro',
      attributes: { status: 'Successful login' },
    },
    {
      id: 'sample-upload:memory:1',
      uploadId: 'sample-upload',
      category: 'memory',
      subtype: 'media',
      sourceFile: 'memories/memories_history.json',
      timestamp: '2026-02-10T00:22:00.000Z',
      contact: null,
      text: null,
      detail: 'IMG_2003.MP4',
      locationName: 'Downtown hotel district',
      latitude: null,
      longitude: null,
      device: null,
      region: null,
      evidenceText: 'IMG_2003.MP4 Downtown hotel district',
      attributes: { filename: 'IMG_2003.MP4' },
    },
    {
      id: 'sample-upload:memory:2',
      uploadId: 'sample-upload',
      category: 'memory',
      subtype: 'media',
      sourceFile: 'memories/memories_history.json',
      timestamp: '2026-02-13T20:25:00.000Z',
      contact: null,
      text: null,
      detail: 'IMG_2011.JPG',
      locationName: 'Hotel lobby',
      latitude: null,
      longitude: null,
      device: null,
      region: null,
      evidenceText: 'IMG_2011.JPG Hotel lobby',
      attributes: { filename: 'IMG_2011.JPG' },
    },
  ],
}
