import type { ParsedUpload } from './types'

export const sampleUpload: ParsedUpload = {
  upload: {
    id: 'sample-upload',
    fileName: 'sample-export.zip',
    sizeBytes: 18342,
    uploadedAt: '2026-02-10T00:00:00.000Z',
    processedAt: '2026-02-10T00:00:00.000Z',
    totalFiles: 5,
    supportedFiles: 5,
    unsupportedFiles: 0,
    categoryCounts: {
      account: 1,
      chat: 4,
      search: 1,
      location: 1,
      login: 1,
      memory: 1,
    },
    account: {
      username: 'alex.viewer',
      displayName: 'Alex Viewer',
      email: 'alex.viewer@example.com',
      phone: '+1 555 555 0199',
      region: 'New York',
      aliases: ['alex.viewer', 'Alex Viewer', 'alex.viewer@example.com'],
    },
    warnings: [],
  },
  fileSummaries: [
    {
      uploadId: 'sample-upload',
      path: 'account/profile.json',
      extension: '.json',
      category: 'account',
      rows: 1,
      supported: true,
    },
    {
      uploadId: 'sample-upload',
      path: 'chats/history.json',
      extension: '.json',
      category: 'chat',
      rows: 4,
      supported: true,
    },
    {
      uploadId: 'sample-upload',
      path: 'search/search_history.json',
      extension: '.json',
      category: 'search',
      rows: 1,
      supported: true,
    },
    {
      uploadId: 'sample-upload',
      path: 'location/location_history.json',
      extension: '.json',
      category: 'location',
      rows: 1,
      supported: true,
    },
    {
      uploadId: 'sample-upload',
      path: 'login/login_history.json',
      extension: '.json',
      category: 'login',
      rows: 1,
      supported: true,
    },
  ],
  events: [
    {
      id: 'sample-upload:chats:1',
      uploadId: 'sample-upload',
      category: 'chat',
      subtype: 'saved message',
      sourceFile: 'chats/history.json',
      timestamp: '2026-02-08T00:41:00.000Z',
      contact: 'Jordan K',
      text: 'Miss you already. Delete this after you read it.',
      detail: null,
      locationName: null,
      latitude: null,
      longitude: null,
      device: null,
      region: null,
      evidenceText: 'Miss you already. Delete this after you read it.',
      attributes: {
        message: 'Miss you already. Delete this after you read it.',
      },
    },
    {
      id: 'sample-upload:chats:2',
      uploadId: 'sample-upload',
      category: 'chat',
      subtype: 'saved message',
      sourceFile: 'chats/history.json',
      timestamp: '2026-02-09T01:14:00.000Z',
      contact: 'Jordan K',
      text: 'When can I see you again?',
      detail: null,
      locationName: null,
      latitude: null,
      longitude: null,
      device: null,
      region: null,
      evidenceText: 'When can I see you again?',
      attributes: {
        message: 'When can I see you again?',
      },
    },
    {
      id: 'sample-upload:search:1',
      uploadId: 'sample-upload',
      category: 'search',
      subtype: 'query',
      sourceFile: 'search/search_history.json',
      timestamp: '2026-02-09T01:10:00.000Z',
      contact: 'Jordan K',
      text: null,
      detail: '@JordanK87',
      locationName: null,
      latitude: null,
      longitude: null,
      device: null,
      region: null,
      evidenceText: '@JordanK87',
      attributes: {
        query: '@JordanK87',
      },
    },
    {
      id: 'sample-upload:location:1',
      uploadId: 'sample-upload',
      category: 'location',
      subtype: 'snap map',
      sourceFile: 'location/location_history.json',
      timestamp: '2026-02-09T01:30:00.000Z',
      contact: null,
      text: null,
      detail: null,
      locationName: 'Downtown hotel district',
      latitude: 40.7127,
      longitude: -74.0059,
      device: null,
      region: 'New York',
      evidenceText: 'Downtown hotel district New York',
      attributes: {
        location: 'Downtown hotel district',
      },
    },
    {
      id: 'sample-upload:login:1',
      uploadId: 'sample-upload',
      category: 'login',
      subtype: 'successful login',
      sourceFile: 'login/login_history.json',
      timestamp: '2026-02-09T01:03:00.000Z',
      contact: null,
      text: null,
      detail: 'Successful login',
      locationName: null,
      latitude: null,
      longitude: null,
      device: 'iPhone 15 Pro',
      region: 'New York',
      evidenceText: 'Successful login iPhone 15 Pro',
      attributes: {
        status: 'Successful login',
      },
    },
    {
      id: 'sample-upload:chats:3',
      uploadId: 'sample-upload',
      category: 'chat',
      subtype: 'saved message',
      sourceFile: 'chats/history.json',
      timestamp: '2026-02-10T00:18:00.000Z',
      contact: 'Jordan K',
      text: 'Thinking about you.',
      detail: null,
      locationName: null,
      latitude: null,
      longitude: null,
      device: null,
      region: null,
      evidenceText: 'Thinking about you.',
      attributes: {
        message: 'Thinking about you.',
      },
    },
    {
      id: 'sample-upload:memory:1',
      uploadId: 'sample-upload',
      category: 'memory',
      subtype: 'media',
      sourceFile: 'memories/memory_history.json',
      timestamp: '2026-02-10T00:22:00.000Z',
      contact: null,
      text: null,
      detail: 'IMG_2003.MP4',
      locationName: 'Downtown hotel district',
      latitude: null,
      longitude: null,
      device: null,
      region: null,
      evidenceText: 'IMG_2003.MP4 Downtown hotel district',
      attributes: {
        filename: 'IMG_2003.MP4',
      },
    },
  ],
}
